### ISSUE TITLE
Login to public OCI registry should not be required

### ISSUE THREAD

**Issue by shlomitk1** [crossplane-contrib/provider-helm#132]
I want to install a public helm chart residing in `oci://ghcr.io` registry. No credentials are required in order to pull the chart. However, if I don't supply `pullSecretRef` , the client still attempts to login to the registry with empty username/password and fails with a message `failed to install release: failed to login to registry:
        Get "https://ghcr.io/v2/": denied`
        
Can the following login command  be skipped if the credentials are empty?
https://github.com/crossplane-contrib/provider-helm/blob/176aa6812860e95712ea7aecd541a564bc839b14/pkg/clients/helm/client.go#L222

**Comment by fbozic** [comment]
Hi folks, 
Do you know if there is any progress on this issue? I can help with implementation if this project is short-staffed.

**Comment by jbw976** [comment]
Hey there @fbozic, I don't know of any ongoing work for this issue. You are more than welcome to open a PR with a proposed fix if you are up for it! 🙏 🙇‍♂️

**Comment by geowalrus4gh** [comment]
That means, i am not able to install an OCI helm chart from a public repository using crossplane ! That's even a basic functionality one would expect from a popular cloud native provisioning tool.

**Comment by kubevalet** [comment]
Just tried using the Helm provider with the DragonflyDB chart here:
```
      name: dragonfly
      repository: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
      version: v1.15.1
```
If failed due to: 
```
  - lastTransitionTime: "2024-04-04T13:26:31Z"
    message: 'create failed: failed to install release: failed to login to registry:
      Get "https://ghcr.io/v2/": denied'
```
Then I found this issue ... a little troubling Crossplane doesn't support OCI helm charts, this is like Helm 101 these days :-( Any known work-around at this point or do we have to wait for #208 to land?

**Comment by jbw976** [comment]
Thank you @kubevalet for sharing your scenario as well - I had just a bit of trouble reproducing this issue while reviewing and testing #208, so your scenario is really helpful. I am able to reproduce the behavior using `oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly`, so I hope we're able to properly review/test/approve #208 soon and get a patch release out with that fix. I am not currently aware of a workaround, so we'll try to drive this to resolution as soon as we can.

Thanks for your patience! 🙇‍♂️

**Comment by jbw976** [comment]
@kubevalet, would you happen to have any suggestions for https://github.com/crossplane-contrib/provider-helm/pull/208#issuecomment-2044718522? Definitely welcoming thoughts/ideas there 😉
