### ISSUE TITLE
make: *** No rule to make target `local.up', needed by `local-dev'.  Stop.

### ISSUE THREAD

**Issue by cmoulliard** [crossplane-contrib/provider-helm#191]
## Issue

The following make commands fail on macos
```
make local-dev
make: *** No rule to make target `local.up', needed by `local-dev'.  Stop.

make help
make: *** No rule to make target `help'.  Stop.
```

**Comment by bobh66** [comment]
Did you run `make submodules` first?  That will initialize the `build` submodule which allows the rest of the `make` commands to work.

**Comment by cmoulliard** [comment]
That fixed the problem. Can you mention it part of the README file please ?
