### ISSUE TITLE
Parallel processing of multiple helm releases

### ISSUE THREAD

**Issue by turkenh** [crossplane-contrib/provider-helm#2]
Processing a Helm `Release` resource could take some time (pulling chart, installing/upgrading helm release). Since they are independent units, we should be able to process them concurrently without waiting one to complete.

[`MaxConcurrentReconciles` option of controller runtime ](https://github.com/kubernetes-sigs/controller-runtime/blob/56938944ad73232915fb2dce719812f99cbf727a/pkg/controller/controller.go#L36)seems like the solution here which we should configure. We can set a sensible default (e.g. 10) or expose it as a configuration option.

**Comment by gberche-orange** [comment]
@turkenh would you have an example of setting the configuration option MaxConcurrentReconciles for helm provider ?

The --max-concurrent-reconciles=100 as an arg in the ControllerConfig failed the helm provider start.
 
 I guess that eventually https://github.com/crossplane/crossplane/issues/2595#issuecomment-983166375 would propagate automatically from crossplane-wide arg `--max-reconcile-rate=100`

**Comment by gberche-orange** [comment]
Edit: I might have misunderstood this PR in thinking a configuration option was introduced in #53, instead only the default MaxConcurrentReconciles=10 was set.
