### ISSUE TITLE
Need a way to read status of a Kubernetes resource deployed with provider-helm

### ISSUE THREAD

**Issue by turkenh** [crossplane-contrib/provider-helm#25]
I have [a composition](https://github.com/crossplane-contrib/provider-helm/blob/7468b80277eb5ac3e87fe7d5d1a207b866f5af48/examples/in-composition/composition.yaml) which includes a managed k8s cluster, a managed db and a helm release which deploys Wordpress application with a new type `WordpressCluster`.

Right now, once composite resource is ready, I need to connect to remote k8s cluster and read status of LoadBalancer type service to get the IP address of wordpress endpoint. I would like my composite resource to report address of wordpress in its status.

To achieve this, we need a way to read LoadBalancer IP in remote cluster, in addition to [composition to support reflecting status of composed resources to composite](https://github.com/crossplane/crossplane/issues/1639).

**Comment by srueg** [comment]
We have exactly the same use case where we create a LoadBalancer service and need to read back the provisioned `loadBalancerIP`.
It would probably also make sense to expose the value in a connection secret?
I couldn't find any support for creating connection secret by this provider, or am I missing something?

**Comment by turkenh** [comment]
This is now possible with: https://github.com/crossplane-contrib/provider-helm/pull/73
