### ISSUE TITLE
New Docker image is not published

### ISSUE THREAD

**Issue by project-administrator** [crossplane-contrib/provider-helm#252]
### What happened?
Trying to install the latest released version 0.20.0 I noticed that the docker image has not been published: 
```
xpkg.upbound.io/crossplane-contrib/provider-helm:v0.20.0
docker.io/crossplanecontrib/provider-helm:v0.20.0
```

### How can we reproduce it?
Attempt to install the latest released version

### What environment did it happen in?
Crossplane version: 
N/A

**Comment by raphasle** [comment]
Hey @project-administrator, I just run in the same "issue" and noticed that the project moved from crossplane-contrib to upbound. So docker pull xpkg.upbound.io/upbound/provider-helm:v0.20.0 actually works.

I noticed it by going to the marketplace where only the new provider can found (https://marketplace.upbound.io/providers/upbound/provider-helm/v0.20.0). For comparison, the old one via direct link: https://marketplace.upbound.io/providers/crossplane-contrib/provider-helm/v0.19.0

A message in the release notes or so would have been nice :D

**Comment by jeanduplessis** [comment]
@raphasle thanks for calling out the lack of notice on the release notes, its been added now: https://github.com/crossplane-contrib/provider-helm/releases/tag/v0.20.0
