### ISSUE TITLE
prometheus charts repo is invalid?

### ISSUE THREAD

**Issue by jbw976** [crossplane-contrib/provider-helm#36]
### What happened?

I created a release.helm.crossplane.io object that points at the `https://prometheus-community.github.io/helm-charts` helm chart repo, but I see an error message that it appears to be invalid:

```
    conditions:
    - lastTransitionTime: "2020-10-20T23:03:59Z"
      message: 'create failed: failed to install release: failed to pull chart: looks
        like "https://prometheus-community.github.io/helm-charts" is not a valid chart
        repository or cannot be reached: open /.cache/helm/repository/Lqeg3VO4wtqr3vbNRjfZ7j2irxk=-index.yaml:
        no such file or directory'
```

I expected this repo to be valid, because the instructions on https://prometheus-community.github.io/helm-charts/ say to do:

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
```

What is invalid about? How can I fix this?

### How can we reproduce it?

This is the full yaml for the release.helm.crossplane.io object I see this with:

```yaml
apiVersion: helm.crossplane.io/v1alpha1
kind: Release
metadata:
  annotations:
    crossplane.io/external-name: platform-ref-aws-cluster-hmfxt-bt279
  creationTimestamp: "2020-10-20T22:29:24Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: platform-ref-aws-cluster-hmfxt-
  generation: 2
  labels:
    crossplane.io/claim-name: platform-ref-aws-cluster
    crossplane.io/claim-namespace: default
    crossplane.io/composite: platform-ref-aws-cluster-hmfxt
  name: platform-ref-aws-cluster-hmfxt-bt279
  ownerReferences:
  - apiVersion: aws.platformref.crossplane.io/v1alpha1
    controller: true
    kind: Services
    name: platform-ref-aws-cluster-hmfxt-sck7l
    uid: 38bb1440-d740-441b-9a92-bd1347967a89
  resourceVersion: "71863"
  selfLink: /apis/helm.crossplane.io/v1alpha1/releases/platform-ref-aws-cluster-hmfxt-bt279
  uid: a5bb45fa-9474-4371-9d7d-269311557033
spec:
  forProvider:
    chart:
      name: kube-prometheus-stack
      pullSecretRef:
        name: ""
        namespace: ""
      repository: https://prometheus-community.github.io/helm-charts
      version: 10.0.2
    namespace: operators
    values: {}
  providerConfigRef:
    name: platform-ref-aws-cluster
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2020-10-20T23:08:01Z"
    message: 'create failed: failed to install release: failed to pull chart: looks
      like "https://prometheus-community.github.io/helm-charts" is not a valid chart
      repository or cannot be reached: open /.cache/helm/repository/X0AUrfHbH+Q4T8EoFX8JnEHnfBU=-index.yaml:
      no such file or directory'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### What environment did it happen in?
Crossplane version: `v0.14.0-rc.27.g225fdf28`
provider-helm version: `v0.3.0`

**Comment by turkenh** [comment]
@jbw976 do you have following env var set in helm provider controller deployment? probably not?

```
    - name: XDG_CACHE_HOME
      value: /tmp
```

**Comment by jbw976** [comment]
No I do not have that in my provider-helm deployment, I can try adding it and seeing if it fixes this @turkenh.

I would expect `kubectl crossplane install provider crossplane/provider-helm:v0.3.0` to take care of this for me.  Do we need to fix something (and where?) so that this works without manual intervention in v0.3.1 or something? 🙏

**Comment by turkenh** [comment]
> I would expect kubectl crossplane install provider crossplane/provider-helm:v0.3.0 to take care of this for me. Do we need to fix something (and where?) so that this works without manual intervention in v0.3.1 or something? 🙏

Yes, this was already case with v0.2.0, but as stated, probably we lost this with new packaging changes. I remember, @hasheddan mentioned somewhere that this might got removed with new packaging (as we now use a static controller deployment). 

Anyway, just pushed a possible fix (#37). It would be great if you could test it in your setup, built and pushed controller image as "turkenh/provider-helm-controller:fix36". Otherwise, I can test tomorrow.

**Comment by jbw976** [comment]
i tested with @turkenh fixed controller from above and now I see this, is it supposed to be transient? its still there after 6-7 mins
```
  status:
    atProvider:
      releaseDescription: Initial install underway
      revision: 1
      state: pending-install
    conditions:
    - lastTransitionTime: "2020-10-20T23:53:15Z"
      message: 'update failed: failed to upgrade release: "platform-ref-aws-cluster-hmfxt-bt279"
        has no deployed releases'
      reason: ReconcileError
      status: "False"
      type: Synced
```

**Comment by turkenh** [comment]
> 'update failed: failed to upgrade release: "platform-ref-aws-cluster-hmfxt-bt279"
        has no deployed releases'

This is because previous installation attempt got interrupted (helm controller pod got terminated for some reason) before it is completed and actual helm release is in `pending-install` state. There is a helm issue for this: https://github.com/helm/helm/issues/7139

So I wouldn't expect this would happen again with a clean installation.

**Comment by turkenh** [comment]
Still to overcome such an edge case:

We have [an optional rollback support](https://github.com/crossplane-contrib/provider-helm/blob/9892ea03768ef631f812c74539870e0e5fe3b0f4/examples/sample/release.yaml#L6) which rolls back latest release and retries which should also start supporting pending states with #37.

**Comment by turkenh** [comment]
@jbw976 `crossplane/provider-helm:v0.3.3` has the fixes.

**Comment by jbw976** [comment]
Tested with v0.3.3 just now and it looks like this issue has been fixed!! thank you @turkenh!
