### ISSUE TITLE
Helm wait option

### ISSUE THREAD

**Issue by turkenh** [crossplane-contrib/provider-helm#4]

**Comment by srueg** [comment]
Would this result in only setting the `Ready` condition on a `Release`, once all resources the chart creates are ready?
If yes it would be a great addition 👍 
Currently the installation of a chart can silently fail (e.g. stuck in pending) and the `Release` still goes into `Ready` state.

**Comment by turkenh** [comment]
Yes, similar to `helm upgrade --install --wait`

It would be an easy addition to make this available as blocking but this is not a good controller pattern. Since, this is already case if chart contains [hooks](https://github.com/crossplane-contrib/provider-helm/issues/58#issuecomment-721083747), may be we can fix this issue simply introducing a blocking wait and track making deployments asynchronous as a [separate issue](https://github.com/crossplane-contrib/provider-helm/issues/63).
