### ISSUE TITLE
Support Helm3 OCI Charts

### ISSUE THREAD

**Issue by benagricola** [crossplane-contrib/provider-helm#75]
### What problem are you facing?
I've been using Helm3 OCI based charts via GitLab container registry due to ease of use, but OCI based charts are not currently supported by `provider-helm`.

### How could Crossplane help solve your problem?
It would be great if OCI based charts could be supported as this _slightly_ lowers the barrier to entry due to not having to run a Helm repo (peak laziness on my behalf!)

Thoughts:

 - How to discern between a normal and an OCI based chart install (Maybe a new `Type` field which defaults to existing behaviour?)
 - How to auth with OCI registry (looks like secret already has a username and password so guessing just calling a different auth method)
 
I'm happy to look at implementing this if the time is right and we can solidify any additions to the API format.

**Comment by benagricola** [comment]
From an implementation perspective this looks pretty simple, but the V2 `pull` action is broken down into a couple of separate steps when using OCI images, these are:

- `NewRegistryLogin`:  Login to the registry at `Repository` using `Username` and `Password`
- `NewChartPull`: Pull OCI Chart Ref from registry into local container cache. This requires a combination of `Name` and `Version` (or new `Ref` field?)
- `NewChartExport`: Export OCI Chart from local container cache. Again based on a Ref field or combination of `Name` and `Version`.

The only problem with actually _doing_ this is that the `ActionConfig.Init` method (from helm) doesn't automatically add a `RegistryClient` instance - and the `RegistryClient` instantiation code (usage [here](https://github.com/helm/helm/blob/cc1d2d62e97ab296e698633d2b81d1455fdfca93/cmd/helm/root.go#L191)) in `helm` is still marked internal so I suspect this needs to wait until that code is made available externally. All comments I can find suggest that was planned for V3.3 or V3.4 but I don't see any change in either of those versions 🕐

**Comment by janwillies** [comment]
It seems this was implemented as part of `v3.5.0`: https://github.com/helm/helm/commit/3ad08f3ea9c09d16ddf6519d65f3f6f2ceee2c37

**Comment by benagricola** [comment]
helm/helm/issues/9188 - looks like moving `registry` out of `internal` is on the roadmap but no solid timescale yet, guess we just have to wait and see 🙂

**Comment by ferhatying** [comment]
OCI integration is moving from experimental to full feature. See also https://github.com/helm/helm/issues/10393. It's currently part of [v3.8.0-rc.1](https://github.com/helm/helm/releases/tag/v3.8.0-rc.1).

**Comment by ferhatying** [comment]
Update: OCI support is now GA in Helm v3.8.0. It's not experimental anymore.
