### ISSUE TITLE
provider-helm hides providerconfigs

### ISSUE THREAD

**Issue by echarles** [crossplane-contrib/provider-helm#89]
### What happened?

Installing `crossplane/provider-helm:master` hides the created `providerconfigs`

### How can we reproduce it?

```
kubectl crossplane install provider crossplane/provider-gcp:master
kubectl crossplane install provider crossplane/provider-helm:master

echo """
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: project_id
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-creds
      key: credentials
""" | kubectl create -f -

kubectl get providerconfig default
Error from server (NotFound): providerconfigs.helm.crossplane.io "default" not found
```

Strangely, the rest continues to work and the default providerconfig can be used when creating infra.

If you skip `kubectl crossplane install provider crossplane/provider-helm:master`, the providerconfig is found.

### What environment did it happen in?

```
kubectl crossplane -v
v1.2.1
```

**Comment by jbw976** [comment]
@echarles this is the somewhat unfortunate (but expected) behavior of `kubectl` when multiple CRDs with the same `Kind` (but different groups) are installed into the cluster.  All the providers have a type called `ProviderConfig`, so you'd see the same behavior if you installed say both `provider-gcp` and `provider-aws`.

I'm not exactly sure how `kubectl` or api-server picks which type has precedence, but to be sure you're doing an operation on the correct type, you should use the fully qualified name - e.g. `providerconfig.gcp.crossplane.io`.

**Comment by echarles** [comment]
I get that it is how kubectl / k8s behaves. I would have hoped that all `ProviderConfig` would be shown, and not only the ones from a single group.

I guess this issue can be closed. It is maybe worth to mention that behavior in the docs.

**Comment by echarles** [comment]
Closing as the reported behavior is expected.

**Comment by muvaf** [comment]
You can also give enough information for kubectl to figure it out, i.e. `providerconfig.gcp` would also work.
